version: "3.8"


name: ProjectDockerComposeAkso


services:
  web:
    image: nginx
    container_name: Nginx_project
    restart: always
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=footbar.com
      - NGINX_PORT=80
    networks:
      - app-network
    init: true
    configs:
      - nginx-config


  db:
    image: mysql
    container_name: mysql_project
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
    ports:
      - "3306:3306"
    networks:
      - app-network
    init: true
    configs:
      - source: mysql-config
        target: /etc/mysql/conf.d/my.cnf


configs:
  nginx-config:
    file: ./nginx.conf
  mysql-config:
    file: ./my.cnf

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
    
